Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### VM SETUP ###
  config.vm.define "devsecops" do |devsecops|
    devsecops.vm.box = "ubuntu/bionic64"
    devsecops.vm.hostname = "devsecops"
	devsecops.vm.network "private_network", ip: "192.168.58.11"
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "10000"
    vb.cpus = 4
  end
	
  end

end
